# Site settings
title: Ben Griffith - Developer blog
email: contact@bgriffith.me
description: > # Description
  I’m a front-end developer based in London who’s always on the look out for a
  challenge and the opportunity to develop myself further on any front. Through
  the experience of leading a team pod, peer collaboration and knowledge sharing
  within development teams have become key principles that I believe help take
  any team to the next level.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bgriffith.me" # the base hostname & protocol for your site
twitter_username: bgriffith_me
github_username:  bgriffith

# Build settings
markdown: kramdown
